[package]
name = "solana_toolbox_anchor"
description = "Toolbox for interacting with an anchor programs using an endpoint"
version = "0.4.4-solana-2.1.4-anchor-0.30.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.97"
anchor-lang = "=0.30.1"

solana-sdk = "=2.1.4"
solana_toolbox_endpoint = "=0.4.4-solana-2.1.4"

[dev-dependencies]
tokio = "1.42.0"
