version: "3"

tasks:
  # General check for mindless complete verification
  check:
    cmds:
      - task fmt
      - task test
      - task lint

  check_web3:
    cmds:
      - task fmt_web3
      - task test_web3
      - task lint_web3

  # Formating
  fmt:
    cmds:
      - task fmt_endpoint
      - task fmt_idl
      - task fmt_anchor
      - task fmt_cli
      - task fmt_web3

  # Testing
  test:
    cmds:
      - task test_endpoint
      - task test_idl
      - task test_anchor
      - task test_cli
      - task test_web3

  # Linting (clippy)
  lint:
    cmds:
      - task lint_endpoint
      - task lint_idl
      - task lint_anchor
      - task lint_cli
      - task lint_web3

  # Publish to cargo
  publish:
    cmds:
      - task publish_endpoint
      - task publish_idl
      - task publish_anchor
      - task publish_cli
      # - task publish_web3

  # Sub-crate Endpoint
  fmt_endpoint:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_endpoint"
    cmds:
      - cargo +nightly fmt
  test_endpoint:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_endpoint"
    cmds:
      - cp Cargo-solana-1.18.26.toml Cargo.toml
      - cargo test {{ .CLI_ARGS }}
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo test {{ .CLI_ARGS }}
  lint_endpoint:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_endpoint"
    cmds:
      - cp Cargo-solana-1.18.26.toml Cargo.toml
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison

  # Sub-crate IDL
  fmt_idl:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_idl"
    cmds:
      - cargo +nightly fmt
  test_idl:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_idl"
    cmds:
      - cp Cargo-solana-1.18.26.toml Cargo.toml
      - cargo test {{ .CLI_ARGS }}
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo test {{ .CLI_ARGS }}
  lint_idl:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_idl"
    cmds:
      - cp Cargo-solana-1.18.26.toml Cargo.toml
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison

  # Sub-crate Anchor
  fmt_anchor:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_anchor"
    cmds:
      - cargo +nightly fmt
  test_anchor:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_anchor"
    cmds:
      - cp Cargo-solana-1.18.26-anchor-0.30.1.toml Cargo.toml
      - cargo test {{ .CLI_ARGS }}
  lint_anchor:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_anchor"
    cmds:
      - cp Cargo-solana-1.18.26-anchor-0.30.1.toml Cargo.toml
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison

  # Sub-crate CLI
  fmt_cli:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_cli"
    cmds:
      - cargo +nightly fmt
  test_cli:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_cli"
    cmds:
      - cargo test {{ .CLI_ARGS }}
  lint_cli:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_cli"
    cmds:
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison

  # Sub-crate Web3
  fmt_web3:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_web3"
    cmds:
      - npm run fmt
  test_web3:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_web3"
    cmds:
      - npm run test {{ .CLI_ARGS }}
  lint_web3:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_web3"
    cmds:
      - npm run lint

  # Publish
  publish_endpoint:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_endpoint"
    cmds:
      - cp Cargo-solana-1.18.26.toml Cargo.toml
      - cargo test
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - git add Cargo.toml
      - git add Cargo.lock
      - git commit -m "publish-0.4.3-endpoint-1.18.26" --allow-empty
      - cargo publish
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo test
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - git add Cargo.toml
      - git add Cargo.lock
      - git commit -m "publish-0.4.3-endpoint-2.1.4" --allow-empty
      - cargo publish
  publish_idl:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_idl"
    cmds:
      - cp Cargo-solana-1.18.26.toml Cargo.toml
      - cargo test
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - git add Cargo.toml
      - git add Cargo.lock
      - git commit -m "publish-0.4.3-idl-1.18.26" --allow-empty
      - cargo publish
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo test
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - git add Cargo.toml
      - git add Cargo.lock
      - git commit -m "publish-0.4.3-idl-2.1.4" --allow-empty
      - cargo publish
  publish_anchor:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_anchor"
    cmds:
      - cp Cargo-solana-1.18.26-anchor-0.30.1.toml Cargo.toml
      - cargo test
      - cargo +nightly clippy
        --all-targets
        -- -D warnings
        --allow=clippy::bool_assert_comparison
      - git add Cargo.toml
      - git add Cargo.lock
      - git commit -m "publish-0.4.3-anchor" --allow-empty
      - cargo publish
  publish_cli:
    dir: "{{ .TASKFILE_DIR }}/solana_toolbox_cli"
    cmds:
      - cp Cargo-solana-2.1.4.toml Cargo.toml
      - cargo test
      #- cargo +nightly clippy
      #  --all-targets
      #  -- -D warnings
      #  --allow=clippy::bool_assert_comparison
      - git add Cargo.toml
      - git add Cargo.lock
      - git commit -m "publish-0.4.3-cli" --allow-empty
      - cargo publish
